// <auto-generated />
namespace DokoMobile.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class relationshipchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relationshipchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202009142104340_relationshipchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
